### ISSUE TITLE
`useQuery` throws fetch errors which cannot be try/catched

### ISSUE THREAD

**Issue by taratatach** [cozy/cozy-client#1031]
When calling `useQuery` in a component, if the request fails for any reason (e.g. the stack cannot be reached), an error will be thrown.
However, we cannot try/catch this error because `useQuery` cannot be in any sort of conditional block.

This results in `Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.` errors in the console.

**Comment by Crash--** [comment]
```
const {fetchStatus} = useQuery('')
//let's say we don't have a network connexion 
console.log({fetchStatus}) // will display errored but it seems that we don't handle the promise rejection :( 
```

But I'm not sure that we will throw any error. So even if you could try / catch, not sure it will work.

Now, if we took a look at react-query,
-  they throw an error in the useQuery hook if needed (https://github.com/tannerlinsley/react-query/blob/2c36b6d9e9cdfcbcacff640e8782274c8e7f6e30/src/react/useBaseQuery.ts#L142). By needed I mean if the app provides an ErrorBoundaries (https://reactjs.org/docs/error-boundaries.html) 
- We can pass an error callback to the useQuery hook to know what to do if there is something in error 


So we can imagine adding an onError property to the useQuery method. Like that, we can specify at the query level what we want to do for an error: 

```
useQuery(QueryDefinition, {as: ..., enabled: ..., fetchPolicy: ..., onError: ...)
```

We can also define the onError callback when creating the 
```
<CozyProvider client={client} onError={e => this.onError(e)} >
```

Like that we declare at the App level the callback 

Does it work fr your use case?

**Comment by flohhhh** [comment]
It seems be a good idea with `CozyProvider` in order to obtain the information globally for the application.

**Comment by Crash--** [comment]
I've a first implementation here: 

https://github.com/cozy/cozy-client/commit/8d02b5166621dd50513763c7ca40379d6fae0e91

Can you test it to see if it works for you?

**Comment by Crash--** [comment]
Closing this issue, you now have an onError callback https://github.com/cozy/cozy-client/pull/1073
