### ISSUE TITLE
_design doc ends up with 2 index definitions

### ISSUE THREAD

**Issue by Merkur39** [cozy/cozy-client#1091]
I have a file "myFile.md" in my Drive (anywhere outside the trash) and the same in the trash.

This request returns both files:
```js
const queryDef = Q(FILES_DOCTYPE)
      .where({ name: "myFile.md" })
      .partialIndex({
        type: 'file',
        trashed: false
      })
      .indexFields(['name'])
```
This request generates this payload:
```json
{
  "selector": {
    "name": "myFile.md"
  },
  "use_index": "_design/by_name",
  "skip": 0
}
```
The problem seems to come from the `use_index`, in db:
```json
{
  "_id": "_design/by_name",
  "_rev": "2-c2c21817c4435fe6316c1038976fb5ce",
  "language": "query",
  "views": {
    "358cf1970125c4d7130143c33fb50472e058acd0": {
      "map": {
        "fields": {
          "name": "asc"
        },
        "partial_filter_selector": {}
      },
      "reduce": "_count",
      "options": {
        "def": {
          "fields": [
            "name"
          ]
        }
      }
    },
    "b046488cf91b15ec368567adcce573798d530f81": {
      "map": {
        "fields": {
          "name": "asc"
        },
        "partial_filter_selector": {
          "trashed": {
            "$eq": false
          }
        }
      },
      "reduce": "_count",
      "options": {
        "def": {
          "fields": [
            "name"
          ],
          "partial_filter_selector": {
            "trashed": false
          }
        }
      }
    }
  }
}
```
There are 2 `views` objects, one with `"partial_filter_selector": {}`, which would explain this bug 🤔

**Comment by paultranvan** [comment]
It seems the index used for your query is the first one defined in the _design doc, thus the one without partial index, which explain why you retrieve the trashed file.
I have to investigate how we can end up with such design index. My guess is that a `_design/by_name` was already existing and it was merged by couchdb when trying to create the one with the partial index. 
So it could be related to https://github.com/cozy/cozy-client/issues/1054

**Comment by Crash--** [comment]
It's clearly related to #1054 👍
