### ISSUE TITLE
Reset de chaque link

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#111]
Lorsque l'utilisateur se déconnecte, nous avons besoin d'oublier toutes ses informations. Chaque `link` ayant potentiellement un état (par exemple Pouch a des données dans des bases de données locales), il faudrait que chaque lien soit resetté.

A première vue, nous pourrions passer par le mécanismes des requêtes déjà implementé dans Cozy-Client : une requête RESET passerait de link en link et chaque link la forwarderait. Le risque serait qu'un lien avec une erreur ne passe pas la requête et que les liens suivants ne soit pas resettés.

Une deuxième solution serait que chaque lien puisse implémenter une méthode `reset` qui serait appellée par le client si elle existe.

**Comment by y-lohse** [comment]
J'ai l'impression que la première solution, en plus d'avoir le problème évoqué de l'erreur-qui-bloque-tout, est un peu un hack — une requête `RESET` n'est pas une requête sur les données l'est un C/R/U/D.

Du coup la seconde option, avec des méthodes sur les links directement, me semble plus adapté lorsque l'on veux changer leur état ou leur comportement. De la même façon qu'on ne va pas faire une requête `init` pour configurer les différents links.

**Comment by drazik** [comment]
J'ai aussi le sentiment que la deuxième solution est plus robuste. 

On demande au client de se `reset`. Il demande à chaque link de se `reset`, en prenant soin de gérer les erreurs dans le cas où un link a lancé une erreur pendant cette phase de reset. `reset` ferait partie de "l'interface" d'un link. Ça me parait propre.

**Comment by edas** [comment]
Effectivement, le cas de _reset_ est peut-être particulier. Ce n'est pas une requête qui passe dans la chaîne des _link_ mais plus une réinitialisation de chaque _link_. Ça me semble sage d'effectivement demander un reset() au client et que ce dernier fasse un foreach sur chaque _link_ plutôt que de créer une chaîne.

Attention par contre. Le reset() doit être synchrone, autant côté client au côté des _link_, sinon on prend le risque qu'une requête soit lancée alors que certains liens sont déjà remis à zéro et pas d'autres.

Peut-être que je suis hors sujet mais… plutôt qu'un reset, si on se déconnecte, est-ce que ce n'est pas tout le client qui devrait être jeté et réinstancié plutôt qu'espérer un `reset()` ?

**Comment by ptbrowne** [comment]
> Attention par contre. Le reset() doit être synchrone, autant côté client au côté des link, sinon on prend le risque qu'une requête soit lancée alors que certains liens sont déjà remis à zéro et pas d'autres.

Le reset de chaque lien ne pourra pas être synchrone : par exemple les destroy() de pouch sont asynchrones. Par contre ce qui peut être synchrone, c'est le changement d'une variable d'état sur le client (client.reset = true) ou comme tu le propose plus loin le fait de le jeter.

**Comment by ptbrowne** [comment]
This has been fixed.
