### ISSUE TITLE
CozyClient - a query may empty the store of an other one / fetchPolicy issue

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-client#1142]
Une requête peut vider le cache d'une autre.

J'ai pas poussé plus le pourquoi du comment mais pour reproduire, sur l'app coachCO2 : 
- faire un hard refresh sur une page d'analyse. Une requete de récupération de data se déclenche alors.
- aller sur la home. Une autre requête se déclenche. Celle-ci vide alors les datas de la requête précédente

En désactivant la fetchPolicy sur la première requête, cela "corrige" le probème.

Il n'y a pas ce comportement si on hard refresh la home, puis qu'on va sur la page d'analyse (même si on fait encore un aller-retour home > analyse)

**Comment by Crash--** [comment]
Logiquement on dispatch un SET_QUERY_RESULT avec l'`id` de la requête (as) et son contenu. On est d'accord que ce SET_Q+UERY_RESULT est bon ? 

Ensuite, est-ce que tu as une action qui touche à ce store ? C'est quoi son SET_QUERY_RESULT ?

**Comment by JF-Cozy** [comment]
Quand je reviens sur la home, j'ai bien un INIT_QUERY qui part.

Dedans, quand je regarde les actions, j'ai bien le bon id de query avec les bonnes valeurs
![image](https://user-images.githubusercontent.com/67680939/157056546-28aa31be-e417-428e-a884-de3ef94d42cc.png)

Dans le RECEIVE_QUERY_RESULT j'ai bien l'attendu également (toujours l'onglet action).

En revanche dans l'onglet diff on voit que les datas ma précédente query on été cleané (on passe d'un count 8 à 0)
![image](https://user-images.githubusercontent.com/67680939/157056890-b9c463f4-6dcc-490f-9383-639e8e7b7669.png)

**Comment by Crash--** [comment]
Tu peux faire voir la gueule du `RECEIVE_QUERY_RESULT` stp ?

**Comment by Crash--** [comment]
@JF-Cozy T'as une branche qu'on peut utiliser avec le souci et nous expliquer comment le reproduire stp ?

**Comment by JF-Cozy** [comment]
@Crash-- oui désolé j'ai été un peu sous l'eau sur d'autre sujet dans CCO2.

Pour reproduire :
- partir de master sur CCO2
- il faut activer le cache sur la requête `buildTimeseriesQueryByDateAndAccountId` en dé-commentant cette ligne https://github.com/cozy/coachCO2/blob/master/src/queries/queries.js#L97
- dans l'app, il faut faire un hard refresh depuis la page d'analyse (n'importe laquelle des deux), aller sur la home, puis revenir sur la page d'analyse initiale => les données du graphique et de la liste (le sélecteur de dates n'est pas impacté) sont alors vides

Tu vas avoir besoin de données dans CCO2, mais un `yarn fixtures` devrait faire l'affaire.

**Comment by JF-Cozy** [comment]
c'est la requête qui n'était pas bonne, voire https://github.com/cozy/coachCO2/pull/102
