### ISSUE TITLE
Models ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#2]
Je copie ici mon [commentaire](https://github.com/cozy/cozy-contacts/pull/40#discussion_r166853439) car j'aimerais savoir quel est votre avis concernant les modèles.

Les besoins :

- Parser les données entrantes
- Formatter les données sortantes pour la UI (formattage de dates, formattage de texte, par exemple dans Bank, nous devons souvent montrer la catégorie d'une opération, cette catégorie pouvant être dans `automaticCategory` ou `manualCategory`; pour éviter la répétition, nous avons un helper getCategoryFromOperation)

Les fonctions de parsing/formatting sont pour le moment souvent organisées dans des fichiers helpers.
Ces fichiers helpers sont parfois organisés dans ducks, parfois appelés utils ou helpers. Cela rend le code non cohérent à travers les applications et pousse le/la développeur(se) à se poser des questions (ce qui n'est pas forcément mauvais :-) ) pour savoir où est ce qu'il/elle doit mettre ces fonctions à chaque fois.

Un modèle d'organisation du code qui couvre ces besoins est le modèle. Personnellement je me demande si ce n'est pas quelque chose que cozy-client devrait pousser plus : 

- Donner un moyen de parser les documents reçus en model
- et/ou donner un moyen de recevoir des models en props
- et/ou donner un moyen de parser les valeurs à l'intérieur des modèles (par exemple les dates)
- et/ou donner un moyen d'organiser ses helpers dans des classes statiques Models

Pour info il y a https://gitlab.cozycloud.cc/labs/cozy-maif/blob/master/src/models/Base.js qui était sur ce modèle non pas de modèle mais de Class avec méthodes statiques pour faire comme si c'était des modèles, mais toujours en travaillant avec des plain old javascript objects.

Dans le connecteur Linxo aussi nous utilisons une technique similaire avec la capacité de parser à partir des documents renvoyés par Linxo : https://gitlab.cozycloud.cc/labs/cozy-konnector-linxo/blob/master/helpers/cozy.js.

Est ce quelque chose dans le scope de cozy-client ?
Ou alors, est ce que ce serait à l'application de faire un modèle à partir des links pour que les méthodes de collection fetch puis parsent ?
Quel est votre avis là dessus ?

---

## Exemple

Besoin : 

* formatter les données pour affichage : trouver l'âge d'un `io.cozy.contacts`

En ce moment ce que nous faisons dans Banks (pour des transactions bancaires mais la technique est la même)

```js
# Import depuis un fichier helper
import { getAge } from 'ducks/contacts/helpers'

const Contact = (prop) => {
  // Utilisation de l'helper  
  return <div>{ prop.contact.name }: { getAge(prop.contact) }</div>
}
```

Les inconvénients que je vois à cette méthode: 

* dur de découvrir la méthode : on ne peut pas utiliser le `debugger` pour taper `contact.<TAB>` et voir la méthode `getAge`
* pas de convention d'ou ranger ces méthodes (question que je me pose souvent: "ou est ce que je met cette méthode?")
* pas de partage du code possible entre les différentes applications
* pas de possibilité de stocker le résultat pour memoizer
* obligation d'import d'une méthode: dur pour le codeur de la classe de refactorer

J'aimerais qu'avec CozyClient nous puissions faire : 

```js
import { Model } from 'cozy-client'

class Contact extends Model {
  getAge () {
    return yearsBetween(Date.now(), this.dateOfBirth) 
  }
}

const schema = {
  'contacts': {
    'io.cozy.contacts': {
      model: Contact 
    }
}

client.registerSchema(schema)
```

Avantage : mémoization aisée : 

```js
  getAge () {
    if (!this._age) {
      this._age = yearsBetween(Date.now(), this.dateOfBirth)
    }
    return this._age
  }
```

Plus besoin d'import : 

```js
const Contact = (prop) => {
  // Utilisation de l'helper  
  return <div>{ prop.contact.name }: { prop.contact.getAge() }</div>
}
```

* Parser les données entrantes: parser la date de naissance d'un contact

Pour que la fonction `yearsBetween` fonctionne il faudrait que l'attribut `dateOfBirth` du contact soit déjà une `Date`. Cela pourrait se faire automatiquement lors de la réception des documents par CozyClient.

```js
class Contact {
  static parse (data) {
    return {
      ...data,
      dateOfBirth: new Date(data.dateOfBirth) 
    }
  }
}
```

`CozyClient` serait 

* responsable de parser les données selon la classe fournie
* instancier les modèles

L'application serait responsable de : 

* définir la classe étendue depuis la base `Model` de `CozyClient`

Inspirations: 

- Backbone.Model : http://backbonejs.org/#Model
- Django Models : https://docs.djangoproject.com/fr/2.0/topics/db/models/
- RubyOnRails Models : https://guides.rubyonrails.org/active_model_basics.html

**Comment by ptbrowne** [comment]
Going back to the EDF app, I found that I used "models" : https://gitlab.cozycloud.cc/labs/cozy-edf/tree/master/src/models

**Comment by enguerran** [comment]
Il semble y avoir plusieurs modes d'utilisation de la lib pour la brancher à du code React/Redux (ou React seul, voire sans React ni Redux) (cf. https://gist.github.com/goldoraf/a4a9acde57002a8da8734810f9fb347d).

Dans quel cadre as-tu besoin de définir un modèle ?

Pour redux, il se placerait dans un sélecteur : `state -> Bills` ou `state -> Contracts`.
Pour react, je ne sais pas si c'est utile.
Pour du code JS (connecteurs par exemple), il se situerait dans l'API du client : `cozyClient.getBills()`.

**Comment by y-lohse** [comment]
> Est ce quelque chose dans le scope de cozy-client ?
> Ou alors, est ce que ce serait à l'application de faire un modèle à partir des links pour que les méthodes de collection fetch puis parsent ?

Je pense que c'est tout à fait dans le scope de cozy-client, mais peut-être qu'on peut commencer par une implémentation dans une app pour tater le terrain. 

> Quel est votre avis là dessus ?

Je vois des cas d'usages pour drive et pour contact, et je suis beaucoup plus à l'aise avec des modèles qu'avec des helpers qui se promènent un peu partout (je sais pas combien de fonction `isDirectory` on a sur drive, mais en tout cas il y en a trop). Du coup assez partant.

Ceci dit je ne parle que de la partie parser / formatter les données. [L'exemple dans cozy-maif](https://gitlab.cozycloud.cc/labs/cozy-maif/blob/master/src/models/Base.js) cité ci-dessus fait aussi des interactions avec le serveur, je serais plus prudent avec ca. Ca a surement sa place aussi, mais il faudrait éviter de se retrouver avec 4 façons différentes de fetcher les mêmes données.

**Comment by ptbrowne** [comment]
>  je serais plus prudent avec ca. Ca a surement sa place aussi, mais il faudrait éviter de se retrouver avec 4 façons différentes de fetcher les mêmes données.

Effectivement, je suis d'accord. Par ailleurs, je pense que c'est une bonne manière de faire une première abstraction au niveau de l'application, avant de le mettre potentiellement dans `cozy-client` (par exemple le cas des relationships) si on trouve le bon niveau d'abstraction.

**Comment by edas** [comment]
> Avantage : mémoization aisée

Je serai très prudent avec ça. Les ORM qui le permettent mettent aussi en place des getter/setter implicites ou explicites pour la totalité des données. Ca leur permet de gérer les cache et les supprimer quand la donnée source est modifiée.

Je doute très fortement que nous ayons envie de gérer cette complexité. Les objets proxy pour les associations sont pour moi le bout de ce qui est envisageable.

Je vous propose plusieurs solutions : 

**1/** On a bien des objets de modèle avec des methodes, mais ces méthodes sont des fonctions pures, sans effet de bord et donc sans changement d'état de l'objet initial. Pas de mémoization donc.

**2/** Les propriétés éventuellement mis en cache sont toutes regroupées dans un sous-objet, et une méthode `clearCache()` permet de les supprimer d'un coup. Ca permet au moins de remettre à zéro tous les effets de bord quand on met à jour un objet métier. 
Le risque c'est d'oublier de le faire, ou que nous finissions par oublier que parfois c'est fait et que nous nous permettions des calculs trop lourds dans les fonctions de memoization.

**3/** On sépare modèle et données. C'est l'approche de Java. Les données sont dans un objet simple. La couche modèle est un proxy qui accède à ces données, implémente les méthodes métier, les transformations et éventuellement les mémoization si on intercepte les écritures des données de base.
Outre le défaut de performance lié à un proxy (et la compatibilité des navigateurs) ça revient à recoder un ORM complexe. J'ai moyen envie d'investir autant sur cette brique aujourd'hui

**4/** On garde un objet utilitaire par type de données, avec des méthodes statiques. C'est un peu ce qu'on fait aujourd'hui mais au lieu d'importer chaque méthode statique individuellement en venant de sources différentes, on fait un seul import qui nous donnent toutes les méthodes liées à un type de donnée précise. C'est plus simple, plus facile (charge éventuellement au fichier importer de lui même importer ses méthodes venant de fichiers tiers).

intuitivement je préfère quelque chose entre la 4 et la 1.

**Comment by ptbrowne** [comment]
Effectivement la memoization peut être un piège. OK pour fonctions pures, ou explicitation de l'éventuel cache.

---

Je pencherais personnellement plus pour la 1 qui à l'avantage de ne pas avoir à importer les méthodes utilitaires.

1: 

```
class TransactionTime extends React.Component () {
	render() {
        const { transaction } = this.props
		return <span>{ transaction.fmtTime() }</span>
	}
}
```

2:

```
import Transaction from 'models/transaction'

class TransactionTime extends React.Component () {
	render() {
        const { transaction } = this.props
		return <span>{ Transaction.fmtTime(transaction) }</span>
	}
}
```

**Comment by ptbrowne** [comment]
I am closing since we have now a `models` folder with a lot of utility functions available on most used doctypes.

**Comment by gregorylegarec** [comment]
Hurrah ! 🎉
