### ISSUE TITLE
Mettre en place une publication automatique sur NPM depuis Travis

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-client#20]
Nous voulons mettre en place une publication automatique de la librairie sur NPM.

Le fonctionnement de lerna est d'avoir un numéro de version dans chaque `packages.json`. Lors d'une nouvelle publication (`yarn lerna publish`) les fichiers `package.json` des différentes librairies sont mise à jour automatiquement. Il faut que l'on push les modifications sur le dépots Github pour que la release sur NPM corresponde.

Une proposition serait de mettre en place [lerna-semantic-release](https://github.com/atlassian/lerna-semantic-release/).

**Comment by ptbrowne** [comment]
Can you precise here why lerna make auto publishing difficult ?

**Comment by ptbrowne** [comment]
It's done now 🎉
