### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#23]
Snapshot Summary
 › 2 snapshot tests failed in 1 test suite. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 5 failed, 11 passed, 16 total
Tests:       6 failed, 109 passed, 115 total
Snapshots:   2 failed, 8 passed, 10 total
Time:        4.146s
Ran all test suites.

**Comment by y-lohse** [comment]
Just a note, aside from fixing the bugs or the tests, we should probably set up travis on this repo to avoid this in the future.

**Comment by enguerran** [comment]
There is a PR that begins the work #30

**Comment by goldoraf** [comment]
Fixed with https://github.com/cozy/cozy-client/pull/30
