### ISSUE TITLE
Problématique du terme `client`

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-client#246]
Actuellement dans `cozy-client` on utilise le terme `client` pour désigner plusieurs choses:
- [cozyClient](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/CozyClient.spec.js#L46) on utilise la même chose coté application
- [cozyStackClient](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/CozyClient.js#L568)

Je serai pour que l'on arrête d'utiliser le mot client et de spécifier à chaque fois `cozyClient` et `stackClient`, de mon coté ça fait plusieurs fois que ça me fait perdre du temps. 

Ça vous est déjà arrivé ? Vous en pensez quoi ?

**Comment by ptbrowne** [comment]
Je serais pour renommer en effet l'attribut `client` du CozyClient en `stackClient`, ce sera effectivement plus clair. Ce sera une breaking change vu que le stack client est parfois utilisé par des applications. La transition peut être géré via un Proxy.

```js
const cozyClient = {
  stackClient: {
    filesCollection: {
      toto: 1
    }
  }
}

const deprecatedHandler = msg => ({
  get(target, prop) {
    console.warn(msg);
    return target[prop];
  },
});


cozyClient.client = new Proxy(cozyClient.stackClient, deprecatedHandler("cozyClient.client is deprecated, prefer to use cozyClient.stackClient"));

console.log(cozyClient.client.filesCollection.toto)
```

**Comment by ptbrowne** [comment]
There are no ambiguity left in the code. `client` is always the CozyClient and stackClient the CozyStackClient.
