### ISSUE TITLE
No schema found for "io.cozy.apps" doctype

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-client#265]
After switching from version 2.0.0 to 2.24.0, a breaking bug is now occuring on cozy-home.

![capture du 2018-11-16 18-02-23](https://user-images.githubusercontent.com/776764/48698711-14e08a80-ebe8-11e8-9608-8e76b25677b3.png)

I did not quickly find how to fix this in the doc or the code, so I came here for help 👼 

How this issue could be tested to avoid future regressions ?

**Comment by gregorylegarec** [comment]
[[HOME] Les applications ne s'affichent plus](https://trello.com/c/ETzfllc2/483-home-les-applications-ne-saffichent-plus)

**Comment by ptbrowne** [comment]
The docs were not explicit on this, sorry. Can you check https://github.com/cozy/cozy-client/pull/266 to see if it makes it clearer ?

**Comment by ptbrowne** [comment]
Fixed by #266

**Comment by gregorylegarec** [comment]
Thanks @ptbrowne 👌
