### ISSUE TITLE
PouchDB and WebSQL

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-client#28]
We are using pouchdb v6, in wich the default adapter for Safari is WebSQL. However, WebSQL is deprecated and has a small cap on the storage.

If there is no specific reason for using pouch v6, I would suggest we switch to Pouch v7.

If we want to stay on Pouch v6, we should make it possible to [configure an adapter](https://pouchdb.com/adapters.html). This would most likely be an option to pass at the beginning.

What do you think ?

**Comment by enguerran** [comment]
Why pouch is mandatory for this client library? (open question)

**Comment by y-lohse** [comment]
If I'm not mistaken, it's only mandatory when using the `PouchDBLink`. It wasn't very clear, but my question was specifically about `PouchDBLink` too :)

**Comment by ptbrowne** [comment]
I personally see no reason why we should not change to PouchDB 7.
