### ISSUE TITLE
Garbage collecting the redux store

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-client#310]
At the moment, we only ever add things to the store. I don't think queries are ever removed, and "orphan" documents that are not linked to a query anymore are never cleaned either.

This means we'll run into situations where a lot of documents will accumulate in memory which might lead to performance issues.

It should be possible to find these orphan documents and clear them from the store to free up memory.

cc @edas

**Comment by ptbrowne** [comment]
This should be possible to do by counting the number of observers of a query. When an ObservableQuery subscribes to a query, we increment the counter of this query, when it unsubscribes, we decrement it. If it reaches 0, we can remove the query content from the store.

**Comment by ptbrowne** [comment]
This has less sense now that we push for queries to be named, thus we should not have a growing `queries` slice.
