### ISSUE TITLE
[cozy-client] Should we drop connect HOC in favor of queryConnect?

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-client#317]
We have two HOCs to connect a react component to a query: `connect` and `queryConnect`. The later can connect multiple queries to a single react component, where the former can connect only one query. So `queryConnect` looks like a enhanced version of `connect`. I think we should keep this one and deprecate then drop `connect`. What do you think?

**Comment by Crash--** [comment]
I'm in favor of having only one HOC. And since `queryConnect` gives us more... 

I like the depreciation and then remove cycle. It gives us some weeks to update our applications.

**Comment by drazik** [comment]
Just talked about it on a meeting: we are going to deprecate `connect` to keep `queryConnect`. PR coming soon.
