### ISSUE TITLE
Optimiser la première synchronisation couch/pouch

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-client#349]
Actuellement lors que l'on fait une synchronisation _couch/pouch_ pour du _offline_ sur mobile, on utilise directement la fonction [`pouch.sync`](https://github.com/cozy/cozy-client/blob/aa674f1bf58641687dc63cfd32900b1bd422d7f3/packages/cozy-pouch-link/src/PouchManager.js#L38) ([voir la documentation](https://pouchdb.com/api.html#sync)). C'est pratique puisque tout est géré par `pouch`.

Avec un Cozy fraichement créé, tout se passe bien et est assez rapide. Si par contre nous avons un Cozy avec du vécu (beaucoup de suppression), alors on se retrouve à faire de la synchronisation d'éléments supprimés et en règle général on en a pas besoin.

Je propose que l'on puisse faire cette première synchronisation sans ses documents supprimés. Après avoir étudié [les différentes façons de filtrer](https://pouchdb.com/api.html#filtered-replication) et une discussion avec @nono voici ce qu'on a imaginé :

1. Récupérer le numéro de séquence (`last_seq`) via un appel au changes feed (`GET /data/:db/_changes?limit=1&since=now`)
2. Récupérer les documents via `GET /data/:db/_all_docs`
3. Insérer les documents dans PouchDB, avec `new_edits: false` ([Voir la doc](https://pouchdb.com/api.html#batch_create))
4. Lancer une réplication avec le numéro de séquence récupéré lors de l'étape 1

Pour la première étape, j'ai remarqué que nous ne pouvions pas facilement avoir les paramètres spécifié, je propose donc [cette PR](https://github.com/cozy/cozy-client/pull/348).

Avez vous des remarques/suggestions ?

**Comment by kosssi** [comment]
Il est impossible de connaitre le nombre de docs effacés a l'avance, chaque utilisateur peut ajouter ça banque supprimer ses comptes les rebrancher ... sur l'application Drive c'est encore différent.

J'ai déjà repéré des documents supprimé contenant encore toutes les infos (je ne suis pas sur que la compaction fonctionne).  

![capture d ecran 2019-01-25 a 10 46 46](https://user-images.githubusercontent.com/1135513/51738084-917f6180-208e-11e9-923d-6e7b5f3c4baa.png)

L'impact est surtout sur le nombre de document puisqu'on les récupère 1000 par 1000.

Pour te donner un exemple concret, on met la première synchronisation sur gangsters.rocks sur l'application Banks 5-6 minutes alors que je pense qu'avec ce changement on serait à 1 minute (c'est de l'etimation).

**Comment by edas** [comment]
C'est bien ma question. Sur Gangster est-ce que tu as une estimation du nombre de docs supprimés et du nombre de docs total ?

Un ratio de 1 à 6 me semble énorme. Sans même compter que la plupart des docs supprimés devraient être vide, ça veut dire que tu penses avoir 5 fois plus de docs supprimés que de docs standard. Quel est le doctype qui te donne un tel ratio ?

Ca mériterait vérification quand même (mais l'idée elle-même ne me semble pas poser de problème)

**Comment by Crash--** [comment]
We had implemented a new strategy for our first synch. See https://github.com/cozy/cozy-client/pull/936
