### ISSUE TITLE
[stackClient] Error prone credentials parameter in fetch

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#368]
The credentials option of `fetch` is error prone IMHO. You might think it is equivalent to the `credentials` option of `fetch` (the global) and that you have to pass `"include"` to send the cookies but no, this option is passed as the value of the Authorization header. So if you do 

`stackClient.fetch('GET', 'route', { credentials: 'include' })` you end up with `"include"` in your `Authorization` header.

I was bitten by this and the fix was simply to remove the options https://github.com/cozy/cozy-client/pull/367 but I think it is very confusing.

I want to remove this part of the code but want to check if this behavior is relied on by anybody.

Relevant part of the code :

https://github.com/cozy/cozy-client/blob/da41842a3becc8efc36af59332d4d0218c5aecb5/packages/cozy-stack-client/src/CozyStackClient.js#L72-L78

**Comment by y-lohse** [comment]
I'm not aware of any app using `options.credentials` to pass in the authorization token, so ok for me.

**Comment by gregorylegarec** [comment]
Ok on our side. ✅
