### ISSUE TITLE
Discussion on Collection

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#374]
From: https://github.com/cozy/cozy-client/issues/372#issuecomment-467786027

I find the Collection APIs in StackClient a bit awkward to use.

When I read `Collection` I expect it to contain documents and to stay around a long time. Here `Collection` happen to be short lived objects (since you cannot store them since you cannot expect the client not to be changed), more fetchers than collections.

Using doctypes (`io.cozy.konnectors`) to access fetching methods is a bit awkard I think and it also feels like an implementation details.

I would prefer to use APIs like that : 

```
stackClient.apps.fetchMaintenanceList()
stackClient.apps.fetchMaintenanceList()
```

It was the case with the old cozy-client-js, I think it was better than the new "Collection" one.

**Comment by gregorylegarec** [comment]
I think I pretty agree with it. 

But we still have the case of regular documents. I feel taht indicating the desired doctype early is a pretty confortable. Maybe it is just a matter a words, and we could keep the `collection` mechanism but rename it to something like `doctype`.

Our API could become
```
stackClient.apps.fetch()
stackClient.triggers.launch()
stackClient.jobs.subscribe() // Yeah realtime seems now natural an easy
stackClient.files.get()
stackClient.doctype('io.cozy.accounts').update()
// etc.
```

**Comment by edas** [comment]
Ok, as long as we only use that pattern for core specific features.

Please take care to not put document/collections methods there (ie: like no `stackClient.contacts.find('…')`

**Comment by gregorylegarec** [comment]
Why does it seems a bad idea to you ?

`stackClient.apps.all()` [needs a dedicated endpoint](https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/AppCollection.js#L27), for example.

**Comment by edas** [comment]
`.apps.all()` is ok for me because we are not addressing the user's document and own couch databases. Looking for apps in the instance is probably a "specific feature" for me (listing contacts in io.cozy.contacts is not).

Still thinking about it
