### ISSUE TITLE
In a query, `sortBy` cannot be used without `where`

### ISSUE THREAD

**Issue by edas** [cozy/cozy-client#405]
In a `queryConnect`, I tried to use `client.find(doctype).sortBy({title: 'desc'})`

*Expected result*: The list of documents sorted by title in descending order

*Alternative expected result*: An exception stating that this syntax isn't supported

*Actual result*: No document, no exception

*Workaround*: Using `client.find(doctype).where({}).sortBy({title: 'desc'})`

Possibly, the `sortBy` clause is only usable if we have a `where` clause. This should propably considered as a bug. In any case, the query shouldn't be silently ignored

**Comment by ptbrowne** [comment]
Would you be interested in trying to solve this bug ?

**Comment by ptbrowne** [comment]
Ping @edas

**Comment by edas** [comment]
J'avais contourné le problème sur le moment. Il ne me parait pas urgent à partir du moment où il est référencé et où le contournement est simple

**Comment by Crash--** [comment]
Just tried, with the new syntax: `client.query(Q('io.cozy.files').sortBy([{'name':'asc'}])` and I got a couch error saying that  the selector is missing. So there is no more silent here, just a database that needs a selector to perform a sort.
