### ISSUE TITLE
Ability to registerPlugin

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#445]
We have several libraries that are for now instantiated each time we need them but I think it would be nice if they could be attached as plugins to the client instance.

This way a component needing realtime for example would just have to do

```
client.realtime
```

instead of 

```
const realtime = new Realtime({ client })
```

It would also be beneficial for things that need resources, for example the realtime where a single socket can be shared across all components needing it.

API I see
```
client.registerPlugin(Intents)
client.registerPlugin(Realtime)
client.registerPlugin(Bar)

class CozyClient {
 registerPlugin(Klass, options) {
    this[Klass.name.toLowerCase()] = new Klass({ ...options, client: this })
  }
}
```

Next user of clients will be able access the plugin :

```
client.realtime.subscribe
client.intents.create
```

Plugin are responsible for hooking up to client lifecycle events to clean up after themselves on logout, instantiate on login etc..

---

Some plugins could be included in the core of client JS and automatically available. Realtime is fairly small for example.

**Comment by Crash--** [comment]
I like the idea of having a plugin system in cozy-client because it means that we can potentially create a kind of interface they should follow. 

Realtime is a good start since it can be very tied to the client. Specially if we bring `realtime : true` to `Query`

**Comment by y-lohse** [comment]
Sounds like a good idea to me as well 👍
