### ISSUE TITLE
cozy-client: must include react to use it

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-client#489]
Even if react is now a peerDependency, cozy-konnector-libs must include react when using cozy-client since index.js imports Provider.js which imports react

**Comment by ptbrowne** [comment]
import CozyClient from "cozyClient/dist/CozyClient" marchera non ?

**Comment by edas** [comment]
I don't understand why it's an issue in cozy-client.

You have a peerDep. If you need it in cozy-konnector-libs, include it in cozy-konnector-libs. If it's depending on what you use in cozy-konnector-libs, then it's up to the konnector to include it or not.

**Comment by ptbrowne** [comment]
I think it is understandably a problem for the user of cozy-konnector-libs to have to do:

```
yarn add cozy-client react
```

when (s)he only wants to use

```
yarn add cozy-client
```

I think using directly the `import CozyClient from "cozy-client/dist/CozyClient"` will solve the problem, maybe an improvement would be to allow `import CozyClient from "cozy-client/CozyClient"`. If we added this in the doc, would it be ok for you @doubleface ?

**Comment by doubleface** [comment]
It's just I did not see the need to put react as a peerDep if you must include react to use cozy-client even if you do not use any react feature

**Comment by ptbrowne** [comment]
> It's just I did not see the need to put react as a peerDep if you must include react to use cozy-client even if you do not use any react feature

Being a peer dep does not mean the dependency is optional. It means that it is the responsibility of the host to install it. It is because cozy-client is used in the context of the React of the application, it does not bring its own version of React, hence we tell yarn/npm not to install a React.

**Comment by drazik** [comment]
We can introduce a `react` entrypoint, so we can `import CozyClient from 'cozy-client'` no matter if we use react or not. And `import { Provider, Query } from 'cozy-client/react'` if we use react.

**Comment by edas** [comment]
> We can introduce a `react` entrypoint, so we can `import CozyClient from 'cozy-client'` no matter if we use react or not. And `import { Provider, Query } from 'cozy-client/react'` if we use react.

I would vote for this but it would also break every react app client of cozy-client.

Would it simply be possible to change Provider.js so it include React through a `require()` with a try/catch and mark it as an optionalDependency?

**Comment by drazik** [comment]
> I would vote for this but it would also break every react app client of cozy-client.

I bet we can write a codemod and ship it with the breaking release. I will try

**Comment by ptbrowne** [comment]
> Would it simply be possible to change Provider.js so it include React through a require() with a try/catch and mark it as an optionalDependency?

I thought it would not work since the resolving of the dependency is done at build time by webpack and I thought webpack would error. BUT it seems webpack is smart enough to statically detect the try/catch and only issue a warning. Without try/catch, we have an error during build.

With try/catch

```
WARNING in ./src/Provider.js
Module not found: Error: Can't resolve 'react' in '/private/tmp/test/src'
 @ ./src/Provider.js
 @ ./src/index.js
```

Without try/catch

```
ERROR in ./src/Provider.js
Module not found: Error: Can't resolve 'react' in '/private/tmp/test/src'
 @ ./src/Provider.js 1:16-32
 @ ./src/index.js
```

So yes I think it is a good solution.

**Comment by edas** [comment]
> > I would vote for this but it would also break every react app client of cozy-client.
> 
> I bet we can write a codemod and ship it with the breaking release. I will try

would be awesome.

I'm in love with codemod

**Comment by doubleface** [comment]
const CozyClient = require('cozy-client/dist/CozyClient') also works actually. And we have to do it also in cozy-doctypes to avoid including react in cozy-konnector-libs

**Comment by ptbrowne** [comment]
> I bet we can write a codemod and ship it with the breaking release. I will try

Building on what drazik started :
https://astexplorer.net/#/gist/dbda709790627b25a6b23a5b51564d09/acb2045bbcc0fc20ed0088c78514f4545d31c229

drazik, would you be up to continue and separate the react entrypoint from the index ? @Crash-- @y-lohse any thoughts ?

**Comment by drazik** [comment]
Yep, this is moving in https://github.com/cozy/cozy-client/pull/494.

**Comment by drazik** [comment]
@doubleface with cozy-client v6.58.0 you should be able to `import CozyClient from 'cozy-client'` without any problem.

**Comment by ptbrowne** [comment]
Closing :)
