### ISSUE TITLE
Query docs is unclear

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#49]
https://github.com/cozy/cozy-client#making-queries

There should be complete description of the DSL.

For example, I don't know how to query for a single document.

**Comment by ptbrowne** [comment]
find
where
all
get -> list dont il faut prendre le premier élément

**Comment by y-lohse** [comment]
The relevant code is [here](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/dsl.js). I don't think it's a good idea to explain the details of all the methods in the README file or they will end up out of sync. So I'm going to use JSDoc as suggested in #57 and see how it can be published.

**Comment by ptbrowne** [comment]
>  I don't think it's a good idea to explain the details of all the methods in the README file or they will end up out of sync.

+1

For information, here is how it is managed in cozy-konnector-libs

https://github.com/konnectors/libs/blob/master/packages/cozy-konnector-libs/package.json#L44

It would be cool if documentation was updated automatically (one pointer: https://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/, not tested, I think it should just be outputted to the docs/ folder instead of a different branch) but we can do it step by step and just do it manually first.

**Comment by y-lohse** [comment]
This issue is taken over by #105.
