### ISSUE TITLE
Ability to connect a Query to a component without fetching ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#50]
I think for now the Query cannot be used only to retrieve a document from the store (and observe its changes) without fetching the document again. When we know that the document is already in the db, it can be useful. I propose to have it as an option in Query ?

```
<Query nofetch query={...} />
```

**Comment by drazik** [comment]
Isn't it the goal of the dedup link ? 

That's what I understand from https://github.com/cozy/cozy-client/blob/master/README.md#network-layer-cozy-link

**Comment by ptbrowne** [comment]
The Dedup link here would deduplicate multiple queries. Here the goal is not to fire at all the query and only react to store changes.

**Comment by ptbrowne** [comment]
Fixed via `fetchPolicy='cache-only'`
