### ISSUE TITLE
Why FETCH_LIMIT is 50 ?

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-client#51]
The default parameter [on stack is 100](https://github.com/cozy/cozy-stack/blob/0c0960e878ffe5c36168a21b55599254c741d3e8/web/data/data.go#L321) so why we don't have the same limitation [here](https://github.com/cozy/cozy-client/blob/389ec4234ece43335fa79ac4114729124150c27a/packages/cozy-stack-client/src/DocumentCollection.js#L5) ?

**Comment by enguerran** [comment]
Paginating is a matter of balance between retrieving all the documents at once, or cutting them into chunks. Without profiling network loads, choosing a value is only a matter of taste.

**Comment by ptbrowne** [comment]
IMHO I think we should avoid to be surprising, I think both the client and the server should have the same limit. Documents are at the moment fairly small. For example on my Cozy, 100 gzipped io.cozy.files is 6kb, 100 `io.cozy.bank.operations` are 9kb.

**Comment by enguerran** [comment]
> both the client and the server should have the same limit

Then the client should not set this value and if he needs to know this value, he can deduce it from the server responses.

**Comment by ptbrowne** [comment]
Seems legit.

**Comment by ptbrowne** [comment]
> Then the client should not set this value and if he needs to know this value, he can deduce it from the server responses.

💯 

Following a discussion with the Gangsters, we agree that cozy-client should not impose a limit by default. If the application wants a limit, it can set it itself.

**Comment by y-lohse** [comment]
> we agree that cozy-client should not impose a limit by default. If the application wants a limit, it can set it itself.

I'm happy with that too. There's still going to be the limit imposed by the server, but I think that's ok.

**Comment by ptbrowne** [comment]
fixed in #120
