### ISSUE TITLE
fetchStatus goes to loading and does not change to loaded

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#526]
It seems that sometimes, a query can be marked as `loading` when in fact it is not loading. This is made more visible when using fetchPolicies since there is no `fetch` whose return callback would set the fetchStatus back to `loaded`.

---

It seems the condition to re-init a query should be changed.

```patch
     // Don't trigger the INIT_QUERY for fetchMore() calls
-    if (existingQuery.fetchStatus !== 'loaded' || !queryDefinition.skip) {
+    if (!existingQuery.lastFetch && existingQuery.fetchStatus !== 'loading') {
```

This way we do not overwrite the status from `loaded` to `loading` when we want to only make sure the query exists in the store.

**Comment by Crash--** [comment]
I'm closing this issue since you fixed the bug in https://github.com/cozy/cozy-client/pull/777
