### ISSUE TITLE
Add a method to fetch myself contact

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-client#580]
The stack now exposes a `POST /contacts/myself` route that returns the current myself contact or creates it if it doesn't exist.

This route returns a document with an `id` property but no `_id` property. That's why in banks we did the following: https://github.com/cozy/cozy-banks/pull/1693/files#diff-ffc373085f47375c5884c1fb5ec91adfR19-R22

As suggested in https://github.com/cozy/cozy-banks/pull/1693#pullrequestreview-325360851, this can be added to cozy-client so apps that want to access to this route don't have to code the same trick

**Comment by Crash--** [comment]
Closing this issue since we have a normalization for myself now https://github.com/cozy/cozy-client/blob/90c7abb13fd71267cb44a1af6bca7b03b03a7645/packages/cozy-stack-client/src/ContactsCollection.js#L23
