### ISSUE TITLE
Mango pitfalls

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#582]
We start to have some tribal knowledge on Mango that would be good to externalize into the documentation.

- Index order (less restrictive to more restrictive, or is it the inverse, I do not remember 😅 )
- Use bookmarks instead of cursor for pagination

**Comment by y-lohse** [comment]
The existing doc page is here https://docs.cozy.io/en/cozy-stack/couchdb-quirks/

**Comment by ptbrowne** [comment]
Closing as duplicate of #751
