### ISSUE TITLE
feat: Only one key for data sent by the stack to the HTML

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#586]
See https://github.com/cozy/cozy-banks/pull/1707/commits/d56d6b3c87dfd866f094c123f9c402b9bc9fe4a0#r355491469 for more details.

Everytime a new piece of data from the stack is necessary, we need to add another key to the HTML template. This is brittle since app developers are in charge of the HTML. IMHO we should reduce the API necessary to communicate data between the stack and app at launch time. IMHO a `data-cozy` attribute would be sufficient and would be better.

This would help us not having to add a key everytime we need a new piece of data from the stack. Additionally, the keys must be conventional and coherent between apps to be correctly picked up by cozy-client or other libs relying on those values, so having the app developer write those keys (and potentially mispelling them) is a risk that could be reduced if there was only one key. The interface would only be between cozy-client and the stack.

**Comment by Crash--** [comment]
I like having an unique stringified object in data-cozy. As you said, it'll be easier to maintain 👍 

All the datas written in the HTML should be accessible from an API end point in order to be able to mock them when we're in a context where the HTML is not served by the stack (mobile app)

**Comment by edas** [comment]
👍  for both comments.

I expect this to be easy on the stack side.

**Comment by ptbrowne** [comment]
This has been done on the stack side.
