### ISSUE TITLE
Dehydratation

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#59]
Sometimes we want to save data to localStorage and for this we need an object that is dehydrated.

Ex: in Banks we have a filter, and we can filter on groups or accounts (two different doctypes, a group containing one or several accounts). We need to store the filtering document in local storage so that after reload, we are still on the same filter. When getting the group object through a query, the association `accounts` is a complex object that is not serializable. I think we should have either a dehydrate method in cozy-client able to remove all complex objects from the object returned by `Query`.

**Comment by y-lohse** [comment]
Could that be part of Models (#2), ie. a `dehydrate` method on the model?

**Comment by ptbrowne** [comment]
Yes

**Comment by ptbrowne** [comment]
Done, there is a `dehydrate` method on the client now.
