### ISSUE TITLE
React to store changes

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#62]
Before, with the Redux store, it was possible to react to the fetching of documents through the RECEIVE_DOCUMENT action, meaning our store could compute complex things only when documents were fetched.

An example would be clearer : in Banks we need to display a curve representing the balance history of an account. For that we take all the transactions, sum their amount by day and we build a list containing all the different account balance by day. 

For now, we compute the balance history in the render and it seems unwise. I was thinking that it may be clearer/better to recompute only when we receive transactions/accounts.

Before the new cozy-client, it was easy to do that since the cozy-store was completely mixed with our store, meaning we could have a reducer react to the RECEIVE_DOCUMENTS action.

Do you think it would be a good idea to do that ?

**Comment by ptbrowne** [comment]
In my case, I finally don't need this because the history is dependent on the potentially active filters, so doing the computation when receiving the results has no sense. Meanwhile, I think we should discuss about this to know where we are going and to know if we want to support something like that.

**Comment by drazik** [comment]
I agree it would be very convenient, but I find it clearer to separate our app's store and cozy-client's store. This way we access the cozy-client data only through its interface.

Maybe we can think about another way to do that ? I'm thinking about some kind of hooks system that we can subscribe to, in which we can dispatch some actions to the app store.

**Comment by ptbrowne** [comment]
> some kind of hooks system that we can subscribe to, in which we can dispatch some actions to the app store.

Something like that ?
```
client.on('receive:data', data => dispatch(computeStuff(data))
```

**Comment by drazik** [comment]
Yes that's the idea. This way we could react to cozy-client events without mixing its internal store and our app store.

The downside I'm thinking about is that maybe we will need to synchronize the two stores and do some things twice sometimes. Which is bad :S
