### ISSUE TITLE
Travis truncate logs when error happens

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#644]
Seems like set -e prevents Travis to correctly pickup logs after
a failure.

Related:

- Thread indicating that set -e can be used in `.travis.yml` scripts:
  https://github.com/travis-ci/travis-ci/issues/1066

- Thread indicating that set -e can cause a problem:
https://github.com/travis-ci/travis-ci/issues/5535

Seems like those two posts are contradictory ? We have to find a way to
make our scripts fail fast without preventing Travis to pickup the logs.

**Comment by Crash--** [comment]
It also seems that automerge is now merging issue even if travis is red :o. I don't know if its related

**Comment by ptbrowne** [comment]
#645 has fixed the problem.
