### ISSUE TITLE
Feature parity between <Query /> and client.query

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-client#646]
Based on:
- https://github.com/cozy/cozy-libs/pull/960#discussion_r380551744
- https://github.com/cozy/cozy-libs/pull/960#discussion_r380556922

The `<Query />` component (or queryConnect) has some extra features compared to calls to `client.query`, and these features could be useful. 

For example it would be good to use fetch policies. One use case for that are calls to `client.query` inside a hook, which will result in many requests.

Another aspect is the `fetchStatus` of the query, as we had to implement a similar mechanism in multiple hooks. Ideally we could use the status kept by cozy-client.

the biggest use case for these are probably within hooks, as most other use cases are covered by `queryConnect`. So this is something to keep in mind when we work on the `useQuery` hook (#547).

**Comment by ptbrowne** [comment]
I think that now that we have useQuery, we can close ?

**Comment by y-lohse** [comment]
Yep, I think so!
