### ISSUE TITLE
Access to intents / fetchJSON

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#67]
For now in Banks we must use cozy-client-js to access `intents` and `fetchJSON`.

**Comment by y-lohse** [comment]
I think the plan is more to have a standalone cozy-interapp lib (sort of like cozy-realtime), rather than integrated with cozy-client. What would be the upside of integrating it here directly ?

**Comment by ptbrowne** [comment]
Since it is not ready yet, I think providing this functionality through the new cozy-client would be a first step. At least in Banks, we would be able to remove cozy-client-js directly.

**Comment by y-lohse** [comment]
Well we definitely want to remove the dependency on cozy-client-js, but I don't know if integrating it in cozy-client while none of them are stable would make things easier.

Looping in @gregorylegarec since he wanted to move cozy-interapp to a standalone lib.

**Comment by ptbrowne** [comment]
Summary of a zoom discussion between @y-lohse and me.

* even if intents is a library, it would be a pain for the user to configure it again, while cozy-client is already configured. `cozy-intents` should be possible to `register` as a plugin to cozy-client. This way, we win on both fronts : modularity/maintability and usability. 
* fetchJSON should be directly transferable to cozy-client

Things to do : 

- [ ] copy/paste fetchJSON to cozy-client
- [ ] simple plugin API : add a `registerPlugin(plugin)` method to cozy-client and a `setupPlugin(client)` to `cozy-intents`

It is still not clear for us if `cozy-intents` is stable enough for `cozy-client` to use it, we need your lights @gregorylegarec :).

**Comment by ptbrowne** [comment]
Intents and realtime are now available as plugins 🎉 

intents: https://github.com/cozy/cozy-libs/tree/master/packages/cozy-interapp
realtime: https://github.com/cozy/cozy-libs/tree/master/packages/cozy-realtime

**Comment by Crash--** [comment]
Are you sure for the intents plugins ;)? I don't think we can do 

```
import {IntentPlugin} from 'cozy-interapp'
client.registerPlugin(IntentPlugin)
```

But yeah, ok for closing the issue, since Intents are pluged to CozyClient by doing const intents = new Intents({ client }) ;)
