### ISSUE TITLE
Improve auto-update queries when a new document arrives

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#68]
When a new document is created, all queries that should contain this document should be touched. For queries with no filtering, this seems easy : we only have to check the _type of the new document and touch all queries with the same type. But for queries that implements some kind of filtering (`.where`), we want to check that the new document belongs to the collections. The definition of the query could be converted to a filtering function and applied to the document to know if it can be inserted in a query. Conversely, when updating a document, we have to check if queries containing the old document should contain the new document, maybe the attribute on which the filtering is done has changed.

**Comment by y-lohse** [comment]
And another thing to keep in mind for the future is ordering on top of filtering. It would presumably work like what you described for the `.where`.
