### ISSUE TITLE
FileUpload Date header

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-client#690]
We can now use xhr to upload file in order to get process callback. But it comes with a drawback... For security reason, Chromium based browser, don't let us set the Date header for a file. (https://bugs.chromium.org/p/chromium/issues/detail?id=38382 & https://stackoverflow.com/questions/6973403/chrome-extension-refuse-header-date-in-ajax-request/6974039 ) 

We use it at two places: 
https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/FileCollection.js#L543

https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/FileCollection.js#L753

We should add a QueryString updated_at & created_at in order to avoid using this Date header. 
It needs a modification of cozy-stack to accept this new updated_at QS.

https://github.com/cozy/cozy-stack/blob/master/web/files/files.go#L153-L163

**Comment by ptbrowne** [comment]
Would you be up to take this issue ?
