### ISSUE TITLE
Perf: Switch from pessimistic index creation to optimistic

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#719]
When launching a query, we need an index. At the moment, we
try to create the index and then we make the query. In the
vast majority of cases, the index is already created so
the first query is useless. We could switch the query logic
to try the query first, and only try to create the index if
the query fails.

**Comment by paultranvan** [comment]
Solved with https://github.com/cozy/cozy-client/pull/857

**Comment by ptbrowne** [comment]
Hurray 🎉
