### ISSUE TITLE
Improved fetchStatus

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-client#736]
cozy-client queries provide a `fetchStatus` string that can be `loading`, `loaded`, `error`, etc. This is good but in practice we still have to write a few checks to decide what we want in the UI, for example [here](https://github.com/cozy/cozy-drive/blob/master/src/drive/web/modules/views/Folder/FolderViewBody.jsx#L39-L48). Maybe we could expose other attributes such as:

- isLoadingInitial
- isLoadingMore
- isError
- isEmpty
- isLoadingForALongTime (helpful to decide if we should show a spinner etc)

**Comment by ptbrowne** [comment]
I am not sure here, it seems it would only increase the API surface with no real improvements. I think it's OK for the app to do some checks on the attributes of the query. I am closing right now, please reopen if you think it should be solved.
