### ISSUE TITLE
Improve documentation about data manipulation

### ISSUE THREAD

**Issue by paultranvan** [cozy/cozy-client#751]
Currently, information about queries, databases details, and more broadly, data manipulation, is dispersed between cozy-client and the stack, leading to partial information sharing and discovery. Typically this [PouchDB](https://github.com/cozy/cozy-stack/blob/master/docs/pouchdb-quirks.md) and [Couchdb](https://github.com/cozy/cozy-stack/blob/master/docs/couchdb-quirks.md) docs provide useful information for front-end developers, but they can very easily miss it. 

It could be interesting to centralize this information, while improving the overall documentation about data manipulation. Typically, the [getting-started tutorial](https://github.com/cozy/cozy-client/blob/master/docs/getting-started.md#how-to-query-with-cozy-client) is very useful, but limited when dealing with more complex queries. 

Maybe we could add an entry "Learn how to manipulate data" directly on the [docs home](https://docs.cozy.io/en/) to centralize information and provide pointers to the cozy-client and stack documentation when required?

**Comment by ptbrowne** [comment]
Why not, it seems a good idea to me. I personnally find the home of the docs not very good since there are 3 big links and I feel that the majority of the space is wasted.

I think also adding the links to https://docs.cozy.io/en/cozy-client/getting-started/ would be good.

**Comment by paultranvan** [comment]
Since https://github.com/cozy/cozy.github.io/pull/181 and https://github.com/cozy/cozy-client/pull/794, I think we can close this issue, even though it can (and will!) still be improved :)
