### ISSUE TITLE
DSL : save(document) 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-client#755]
Save currently only takes a document (https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/CozyClient.js#L410). We should be able to provide an array of documents to save and then having an `UPDATE_DOCUMENTS` mutation that execute https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/DocumentCollection.js#L282 

It'll be faster to use bulk_docs instead :)

It seems that there is no updateAll yet on the PouchLink

**Comment by JF-Cozy** [comment]
Same issue here https://github.com/cozy/cozy-client/issues/694 I presume

**Comment by ptbrowne** [comment]
Closing since it's a duplicate of #694 .
