### ISSUE TITLE
Ability to use a filtered query while using the /jobs/trigger route

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#767]
The /jobs/trigger route adds the `current_state` attribute.
At the moment, this route is not used when using a `.where` query
on the triggers. This would be useful when an application only wants
to query some triggers and does not want to do the filtering on the
client-side.

See https://github.com/cozy/cozy-banks/commit/fe39e77e472848c66890c18f826413cb011dc8e7
for more details.

The doc of the /jobs/triggers route is here : https://docs.cozy.io/en/cozy-stack/jobs/#get-jobstriggers
At the moment, it only accepts a Worker parameter. Maybe it could support a Selector parameters to be more versatile ?

**Comment by ptbrowne** [comment]
cc @nono, should I close this issue ?

**Comment by nono** [comment]
Yep, let's close this issue.
