### ISSUE TITLE
All() returns documents without _id

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-client#812]
When doing : 

```
client
                .all('io.cozy.files.versions')
                .where({
                  relationships: { file: { data: { _id: fileId } } },
                  updated_at: { $gt: null }
                })
                .sortBy([
                  { 'relationships.file.data._id': 'desc' },
                  { updated_at: 'desc' }
                ])
                .indexFields(['relationships.file.data._id', 'updated_at'])
            }
```

The returned data doesn't have an `id` (CouchDocument doesn't have one https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.files.md#iocozyfilesversions but we should normalize the document, no ? https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/DocumentCollection.js#L23-L26

**Comment by ptbrowne** [comment]
Yes the data should be normalized, it is a bug otherwise.

**Comment by Crash--** [comment]
I think I smoked too much. There is no bug, it works well and it already well tested.
