### ISSUE TITLE
Bug in the store when deleting a document of Photos

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-client#844]
I had to revert this https://github.com/cozy/cozy-drive/pull/2200 since we have a bug when calling destroy(). (to reproduce, you only have to delete a photo in the timeline) 

The deleted document is tagged as toUpdate https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/store/queries.js#L213 but it should be tagged as to Remove. 

I don't know if the bug is due to the partialIndex in the query or the selector or else... But it seems to come from `isFulfilled` method 

I create the issue to track it.

**Comment by paultranvan** [comment]
Might be related to https://github.com/cozy/cozy-client/pull/846
