### ISSUE TITLE
Partial indexes param are not taken into account

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-client#845]
Since https://github.com/cozy/cozy-client/issues/750 we have implemented partial indexes https://github.com/cozy/cozy-client/pull/838

We tested it in Contacts : https://github.com/cozy/cozy-contacts/blob/2a143ca09c1a156411cebc25c28df9c72dda5719/src/helpers/queries.js#L70

The problem is: the queries with partial index return the expected documents from the server-side, but are not correctly interpreted in the cozy-client store: it seems that as we use [sift](https://www.npmjs.com/package/sift) to query docs in the store based on the selector only, the filter expressed in the partial index is not taken into account. 
Typically, for contacts, the query [contactsWithoutIndexes](https://github.com/cozy/cozy-contacts/blob/master/src/helpers/queries.js#L70) returns contacts according to the partialIndex rules, but cozy-client will base the query only on the selector part, i.e.  `.where({ _id: { $gt: null } })`, which will return all the contacts. 
As as result, there are duplicates after adding a contact, coming from both query, `contactWithoutIndexes` and `contactsWithIndexes`.

**Comment by ptbrowne** [comment]
It seems it should be possible to be fixed here : https://github.com/cozy/cozy-client/blob/351129a1737565f1a6e46b011fa1f0cbb14ef858/packages/cozy-client/src/store/queries.js#L142, @JF-Cozy, I see that @paultranvan is assigned but would you be up to take this task ?
