### ISSUE TITLE
Allow for serial queries

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#869]
At the moment, we do not support serial queries since we cannot put
ifs around useQuery.

Here is a simple exampel where we need the accountId from the trigger to be
able to execute the request.

The `enabled` prop here is following react-query API : the second useQuery will
only be sent if accountId is defined.

```jsx
import get from 'lodash/get'

const useKonnectorData = ({ konnectorId, triggerId }) => {

    const { data: trigger } = useQuery(Q('io.cozy.triggers').getById(triggerId))

    const accountId = get(trigger, 'message.account')
    const account = useQuery(Q('io.cozy.accounts').getById(accountId), { enabled: !!accountId})
}
```

**Comment by Crash--** [comment]
I like the idea of having an `enabled` argument!

**Comment by Crash--** [comment]
Done by https://github.com/cozy/cozy-client/commit/6faede4f590ef2a9f2e5fb53603d6beb035f71f9

Thanks!
