### ISSUE TITLE
Move useRealtime hook in Cozy Realtime 

### ISSUE THREAD

**Issue by flohhhh** [cozy/cozy-client#899]
it makes more sense to have [useRealtime hook](https://github.com/cozy/cozy-ui/blob/master/react/hooks/useRealtime.js) in [cozy-realtime project](https://github.com/cozy/cozy-libs/tree/master/packages/cozy-realtime)

**Comment by ptbrowne** [comment]
cozy-realtime repo is https://github.com/cozy/cozy-libs ;)

**Comment by Crash--** [comment]
Closing it since we now have a useRealtime in cozy-realtime https://github.com/cozy/cozy-libs/blob/master/packages/cozy-realtime/src/useRealtime.js 

Still, we should deprecate the one in UI
