### ISSUE TITLE
Cozy-Client : queries should respect the limitBy argument

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-client#901]
Following https://github.com/cozy/cozy-libs/pull/1279#discussion_r592549449 

> queries inside cozy-client do not respect the limitBy parameter since we want to be able to fetchMore. This is a bit tricky.

Queries inside cozy-client should respect the limitBy argument!

**Comment by ptbrowne** [comment]
I am not sure about that.

The current semantic of limitBy is to limit the number of documents *transferred*, and it can happen sometimes that that this coincides with the need of limiting the number of documents *displayed*, but I am not sure that we should conflate the two semantics.

For example, if we used the limitBy limit to cap the number of documents inside the query, we would have problems when calling fetchMore:

- When calling fetchMore on a query that has limitBy, what should happen ? Query n documents and discard the other ones ? I do not think we want to discard and the fetchMore behavior right now seems to be reasonable (fetching more documents and adding them to the current query results, without discarding any document). 

It seems like being able to control the number of documents displayed can be done easily with a slice on the query results.

If we want a behavior where there is a hard limit on the documents stored inside the collection, I think we should use something other than `limitBy`, maybe putting a *cap limit* on the query ?
