### ISSUE TITLE
OAuth2 & URL redirect. Should the parameter be code instead of access_code?

### ISSUE THREAD

**Issue by prebours** [cozy/cozy-client#91]
Hello:

As per the OAuth2 [documentation](https://aaronparecki.com/oauth-2-simplified/), it seems that the redirect url should contain `code` as a parameter. But cozy-stack returns `access_code`. The problem is that the OAuth implementation of cozy does not work well with external libraries. FYI, I am using `httr` that is a *R* package specialized in REST queries.

This is the code found in *cozy-stack-client*:

```
getAccessCodeFromURL(pageURL, stateCode) {
    if (!stateCode) throw new Error('Missing state code')

    const params = new URL(pageURL).searchParams
    const urlStateCode = params.get('state')
    const urlAccessCode = params.get('access_code')

    if (stateCode !== urlStateCode)
      throw new Error('Given state does not match url query state')

    return urlAccessCode
  }
```

**Comment by y-lohse** [comment]
Hi @prebours !

i'm not sure why we're using `access_code` over `code`, but the right people are over on cozy/cozy-stack. [I've taken the liberty to ask your question there](https://github.com/cozy/cozy-stack/issues/1488) as it's a more appropriate place for it, and I'll close this issue.
