### ISSUE TITLE
could not find react-redux context value when using useQuery

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-client#910]
:wave:

I am trying to use the `useQuery` hook to fetch some documents, but it throws the following error:

```
Uncaught Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
```

I have a `CozyProvider` in `src/targets/browser/index.jsx`:

```jsx
const renderApp = function(client) {
  const App = require('components/App').default
  render(
    <CozyProvider client={client}>
      <App />
    </CozyProvider>,
    document.querySelector('[role=application]')
  )
}

//...

document.addEventListener("DOMContentLoaded", () => {
  const client = CozyClient.fromDOM({ schema })
  renderApp(client)
})
```

The App component contains routing logic (`src/components/App.jsx`):

```jsx
const App = () => {
  return (
    <HashRouter>
      <Layout>
        <Switch>
          <Route path="/music" component={TracksList} />
          <Redirect from="/" to="/music" />
          <Redirect from="*" to="/music" />
        </Switch>
        <IconSprite />
      </Layout>
    </HashRouter>
  )
}
```

In the TracksList component I try to fetch `io.cozy.files` documents (`src/components/TracksList.jsx`):

```jsx
export const TracksList = () => {
  const query = Q("io.cozy.files")
  const queryResult = useQuery(query, { as: "files" })

  return (
    isQueryLoading(queryResult) ? <p>Loading...</p> : <p>Loaded</p>
  )
}
```

To check if it's specific to `useQuery`, I tried to use the `Query` component instead by doing:

```jsx
export const TracksList = () => {
  const query = Q("io.cozy.files")

  return (
    <Query query={query} as="files">
      {(queryResult) => isQueryLoading(queryResult) ? <h1>Loading...</h1> : <p>Loaded</p>}
    </Query>
  )
}
```

And in this case it works fine. It seems I'm doing something wrong with `useQuery` :thinking: But I didn't find docs about it on https://docs.cozy.io/en/cozy-client/react-integration/ and I searched for usage examples in existing cozy apps codebases but I couldn't find a meaningful difference with my code.

**Comment by ptbrowne** [comment]
Ah yes, useQuery uses `useSelector from `react-redux` and you have to put a ReduxProvider. I guess we could do it by default in CozyProvider and have a prop to deactivate it if the app uses its own ReduxProvider. What do you think ?

```patch
+ import { Provider as ReduxProvider } from 'react-redux'
+    client.ensureStore()
    <CozyProvider client={client}>
+      <ReduxProvider store={client.store}>
        <App />
+      </ReduxProvider>
    </CozyProvider>,
```

**Comment by ptbrowne** [comment]
I think we could remove the need for a ReduxProvider by using the createSelectorHook function from redux : https://github.com/reduxjs/react-redux/blob/65b4a16ef12fb596a8a41050bb15cef7e9e7e2b6/src/hooks/useSelector.js#L102

Would be up to take a look ? In the meantime I updated the docs in https://github.com/cozy/cozy-client/pull/911, can you tell me if it's clearer ?

**Comment by ptbrowne** [comment]
Should be fixed by #911, tell me if you need to reopen ;)

**Comment by drazik** [comment]
@ptbrowne I just upgraded cozy-client to v21.0.1 which includes #911. But now I have the following error: `Uncaught TypeError: store is undefined`.

It works if I add a `client.ensureStore()` before rendering the app though.

**Comment by ptbrowne** [comment]
OK I'll need to look into that and check if we should always have a store. I do not see why we should not have this by default. I think we had not created the store automatically to allow the user to use its own redux store but it should be opt in via an option.

```
new CozyClient({
  createStore: false
})
```

So by default, the client would do ensureStore in the constructor unless the user pass `createStore: false`, and in this case the user is responsible to call setStore() or ensureStore(). What do you think ?

**Comment by drazik** [comment]
Sounds good.

I have another suggestion: would it be possible for the user to pass a store to the constructor? If the user gives a store, then `CozyClient` uses it, otherwise it creates its own one.

**Comment by ptbrowne** [comment]
My problem is that when you want to use plug your own store, you have to create the client before the store so that you can wire the client reducer inside the redux store:

```
const client = new CozyClient()
const reducer = combineReducers({
  cozy: client.reducer(),
  // ...other reducers
})
const store = createStore(reducer)
client.setStore(store)
```

This is why we allow for the delay between client instanciation and the instance being bound to the store.

But yes, we could have the `store` option instead of `createStore`.

```
const client = new CozyClient() // by default ensureStore() is called
const client2 = new CozyClient({ store: myStore }) // use this redux store (here you would need to call store.replaceReducer to bind the client reducer
const client3 = new CozyClient({ store: false }) // do not create a store, let me call setStore
```

?

**Comment by drazik** [comment]
Oh I see, I forgot that we have to call `client.reducer`.

Can't we call `store.replaceReducer` in the constructor so it's transparent for the user?

**Comment by ptbrowne** [comment]
> Can't we call store.replaceReducer in the constructor so it's transparent for the user?

I am not sure I want to transfer control of the existing app store to the client. Because to replace the reducer, you'd have to know the existing reducer and inject the `client` object inside the return value of the existing reducer. I think it's preferable for the user to do it, it's less magical.

AMHA the DX experience is ok here. You start by not mixing the two stores, and when you need it, you can "eject" (to borrow CRA terminology) from the default store creation, and add your reducer.

**Comment by drazik** [comment]
Yes you're right. I think it's a good way to solve this :+1:
