### ISSUE TITLE
Prevent multiple fetch more

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#982]
A recent bug in banks was due to multiple fetchMore being called, and
the app was not waiting for fetchMore to be finished.

When discussing in daily with @julienf, we wondered if as for client.query(), should fetchMore do nothing if one fetchMore is already in flight ?

It makes sense for me when thinking about multiple components that could
fetchMore on a collection, and it is hard for the app to coordinate them.

On the other way, it seems that it could hide applicative bugs. I am
a bit wary of introducing "smart" features like this.

Maybe a middle ground could be to issue a warning and still do the fetch ?

**Comment by Crash--** [comment]
Closing it since we now have a `dedup` phase for every request. fetchMore should also be concerned.
